version: '3'

services:
  app:
    build: .
    command: python3 app/manage.py runserver 0.0.0.0:8080
    volumes:
      - ./apps:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment: 
      MYSQL_NAME: django
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
  db:
    image: mysql:5.7
    volumes: 
      - ./docker/data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: django
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"